/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CFH;

import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lhd
 */
public class frmQLMaKM extends javax.swing.JFrame {

    /**
     * Creates new form ProductManagement
     */
    public frmQLMaKM() {
        initComponents();
        showListMaKM();
        setButtonKM(true);
        setEnableKM(false);
    }

    Controller c = new Controller();
    boolean add = false;

    void showListMaKM() {
        DefaultTableModel model = (DefaultTableModel) tbListMaKM.getModel();
        try {
            ResultSet rs = c.showMaKM();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt("MaKM"), rs.getString("TenKM"), rs.getInt("PhanTram"), rs.getString("NoiDung")});
            }
        } catch (SQLException sql) {

        }
    }

    void setNullKM() {
        txtMaKM.setText("");
        txtTenKM.setText("");
        txtPhanTram.setText("");
        txtNoiDung.setText("");
    }

    void setEnableKM(boolean e) {
        txtTenKM.setEditable(e);
        txtPhanTram.setEditable(e);
        txtNoiDung.setEditable(e);
    }

    void setButtonKM(boolean b) {
        btnAdd.setEnabled(b);
        btnUpdate.setEnabled(b);
        btnDelete.setEnabled(b);
        btnSave.setEnabled(!b);
        btnCancel.setEnabled(!b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNameTU2 = new javax.swing.JLabel();
        txtTenThucUong2 = new javax.swing.JTextField();
        jPanelHeader = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        lbFrmTitle = new javax.swing.JLabel();
        jPanelPrdManagement = new javax.swing.JPanel();
        lbMaLoai = new javax.swing.JLabel();
        lbNameTU = new javax.swing.JLabel();
        txtMaKM = new javax.swing.JTextField();
        txtTenKM = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lbPhanTram = new javax.swing.JLabel();
        txtPhanTram = new javax.swing.JTextField();
        lbNoiDung = new javax.swing.JLabel();
        txtNoiDung = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListMaKM = new javax.swing.JTable();

        lbNameTU2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNameTU2.setText("Tên khuyến mãi");

        txtTenThucUong2.setBackground(new java.awt.Color(238, 238, 238));
        txtTenThucUong2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenThucUong2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTenThucUong2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lí sản phẩm");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setName("frameProductManagement"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(810, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHeader.setBackground(new java.awt.Color(234, 128, 37));

        lbLogo.setBackground(new java.awt.Color(255, 255, 255));
        lbLogo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbLogo.setForeground(new java.awt.Color(255, 255, 255));
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CFH/images/logo.png"))); // NOI18N
        lbLogo.setText("The CàPhê House");

        lbFrmTitle.setBackground(new java.awt.Color(255, 255, 255));
        lbFrmTitle.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbFrmTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbFrmTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFrmTitle.setText("Quản lí khuyến mãi");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbFrmTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFrmTitle))
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 110));

        jPanelPrdManagement.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPrdManagement.setLayout(null);

        lbMaLoai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMaLoai.setText("Mã khuyến mãi");
        jPanelPrdManagement.add(lbMaLoai);
        lbMaLoai.setBounds(30, 20, 110, 32);

        lbNameTU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNameTU.setText("Tên khuyến mãi");
        jPanelPrdManagement.add(lbNameTU);
        lbNameTU.setBounds(30, 80, 110, 20);

        txtMaKM.setEditable(false);
        txtMaKM.setBackground(new java.awt.Color(238, 238, 238));
        txtMaKM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaKM.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMaKM.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        jPanelPrdManagement.add(txtMaKM);
        txtMaKM.setBounds(180, 30, 220, 32);

        txtTenKM.setEditable(false);
        txtTenKM.setBackground(new java.awt.Color(238, 238, 238));
        txtTenKM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenKM.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTenKM.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        txtTenKM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenKMKeyReleased(evt);
            }
        });
        jPanelPrdManagement.add(txtTenKM);
        txtTenKM.setBounds(180, 80, 220, 32);

        btnAdd.setBackground(new java.awt.Color(204, 204, 204));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.setBorder(null);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanelPrdManagement.add(btnAdd);
        btnAdd.setBounds(30, 250, 100, 36);

        btnUpdate.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.setBorder(null);
        btnUpdate.setBorderPainted(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanelPrdManagement.add(btnUpdate);
        btnUpdate.setBounds(140, 250, 100, 36);

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.setBorder(null);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanelPrdManagement.add(btnDelete);
        btnDelete.setBounds(250, 250, 100, 36);

        btnSave.setBackground(new java.awt.Color(204, 204, 204));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setText("Lưu");
        btnSave.setBorder(null);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanelPrdManagement.add(btnSave);
        btnSave.setBounds(360, 250, 100, 36);

        btnCancel.setBackground(new java.awt.Color(204, 204, 204));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setText("Hủy");
        btnCancel.setBorder(null);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanelPrdManagement.add(btnCancel);
        btnCancel.setBounds(470, 250, 100, 36);

        lbPhanTram.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbPhanTram.setText("Phần trăm");
        jPanelPrdManagement.add(lbPhanTram);
        lbPhanTram.setBounds(30, 140, 110, 20);

        txtPhanTram.setBackground(new java.awt.Color(238, 238, 238));
        txtPhanTram.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPhanTram.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPhanTram.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        txtPhanTram.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhanTramKeyReleased(evt);
            }
        });
        jPanelPrdManagement.add(txtPhanTram);
        txtPhanTram.setBounds(180, 130, 217, 32);

        lbNoiDung.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNoiDung.setText("Nội dung");
        jPanelPrdManagement.add(lbNoiDung);
        lbNoiDung.setBounds(30, 200, 110, 20);

        txtNoiDung.setBackground(new java.awt.Color(238, 238, 238));
        txtNoiDung.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNoiDung.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNoiDung.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        jPanelPrdManagement.add(txtNoiDung);
        txtNoiDung.setBounds(180, 190, 217, 32);

        tbListMaKM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbListMaKM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khuyến mãi", "Tên khuyến mãi", "Phần trăm", "Nội dung"
            }
        ));
        tbListMaKM.setColumnSelectionAllowed(true);
        tbListMaKM.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbListMaKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListMaKMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbListMaKM);
        tbListMaKM.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanelPrdManagement.add(jScrollPane1);
        jScrollPane1.setBounds(10, 297, 580, 260);

        getContentPane().add(jPanelPrdManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 600, 570));

        setSize(new java.awt.Dimension(607, 718));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbListMaKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListMaKMMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbListMaKM.getModel();
        int index = tbListMaKM.getSelectedRow();
        txtMaKM.setText((model.getValueAt(index, 0)).toString());
        txtTenKM.setText((model.getValueAt(index, 1)).toString());
        txtPhanTram.setText(model.getValueAt(index, 2).toString());
        txtNoiDung.setText(model.getValueAt(index, 3).toString());
    }//GEN-LAST:event_tbListMaKMMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        setButtonKM(false);
        setNullKM();
        setEnableKM(true);
        add = true;
        txtTenKM.requestFocus();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnCancel.setEnabled(true);
        DefaultTableModel model = (DefaultTableModel) tbListMaKM.getModel();
        if (tbListMaKM.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn khuyến mãi muốn sửa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            setButtonKM(false);
            setEnableKM(true);
            add = false;
            txtTenKM.requestFocus();
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbListMaKM.getModel();
        if (tbListMaKM.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn khuyến mãi muốn xóa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                int ma = Integer.parseInt(txtMaKM.getText());
                c.DeleteKM(ma);
                JOptionPane.showMessageDialog(this, "Bạn đã xóa khuyến mãi thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                model.setRowCount(0);
                showListMaKM();
            } catch (SQLException sql) {

            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int pt = 0;
        DefaultTableModel model = (DefaultTableModel) tbListMaKM.getModel();
        if (add) {
            try {
                if (txtNoiDung.getText().equals("") || txtTenKM.getText().equals("") || txtPhanTram.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Hãy nhập đầy đủ các ô", "Thông báo", JOptionPane.INFORMATION_MESSAGE);  
                } else {
                    pt = Integer.parseInt(txtPhanTram.getText());
                    c.InsertKM(txtTenKM.getText(), pt, txtNoiDung.getText());
                    JOptionPane.showMessageDialog(this, "Bạn đã thêm sản phẩm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    model.setRowCount(0);
                    setEnableKM(false);
                    setButtonKM(true);
                    setNullKM();
                    showListMaKM();
                }

            } catch (SQLException sql) {

            }
        } else {
            int ma = 0;
            try {
                if (txtNoiDung.getText().equals("") || txtTenKM.getText().equals("") || txtPhanTram.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Hãy nhập đầy đủ các ô", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    ma = Integer.parseInt(txtMaKM.getText());
                    c.UpdateKM(ma, txtTenKM.getText(), pt, txtNoiDung.getText());
                    JOptionPane.showMessageDialog(this, "Bạn đã sửa sản phẩm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    model.setRowCount(0);
                    setEnableKM(false);
                    setButtonKM(true);
                    setNullKM();
                    showListMaKM();
                }

            } catch (SQLException sql) {

            }
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        setNullKM();
        setButtonKM(true);
        setEnableKM(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtTenKMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenKMKeyReleased
        // TODO add your handling code here:
        if (!txtTenKM.getText().matches("^[0-9a-zA-Z]*$")) {
            JOptionPane.showMessageDialog(this, "Không được nhập kí tự đặc biệt", "Sai kiểu dữ liệu", JOptionPane.INFORMATION_MESSAGE);
            txtTenKM.setText("");
        }
    }//GEN-LAST:event_txtTenKMKeyReleased

    private void txtPhanTramKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhanTramKeyReleased
        // TODO add your handling code here:
        if (!txtPhanTram.getText().matches("^[0-9]*$")) {
            JOptionPane.showMessageDialog(this, "Hãy nhập số", "Sai kiểu dữ liệu", JOptionPane.INFORMATION_MESSAGE);
            txtPhanTram.setText("");
        }
    }//GEN-LAST:event_txtPhanTramKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQLMaKM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQLMaKM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQLMaKM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQLMaKM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQLMaKM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelPrdManagement;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbFrmTitle;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbMaLoai;
    private javax.swing.JLabel lbNameTU;
    private javax.swing.JLabel lbNameTU2;
    private javax.swing.JLabel lbNoiDung;
    private javax.swing.JLabel lbPhanTram;
    private javax.swing.JTable tbListMaKM;
    private javax.swing.JTextField txtMaKM;
    private javax.swing.JTextField txtNoiDung;
    private javax.swing.JTextField txtPhanTram;
    private javax.swing.JTextField txtTenKM;
    private javax.swing.JTextField txtTenThucUong2;
    // End of variables declaration//GEN-END:variables
}
