/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CFH;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lhd
 */
public class frmQLSP extends javax.swing.JFrame {

    /**
     * Creates new form ProductManagement
     */
    public frmQLSP() {
        initComponents();
        showTenLoai();
        showListSP();
        setEnableSP(false);
        setButtonSP(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        lbFrmTitle = new javax.swing.JLabel();
        jPanelPrdManagement = new javax.swing.JPanel();
        cbbTenLoai = new javax.swing.JComboBox<>();
        lbMaTU = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();
        lbNameTU = new javax.swing.JLabel();
        txtTenThucUong = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        txtMaThucUong = new javax.swing.JTextField();
        lblbTenLoai = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListSP = new javax.swing.JTable();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lí sản phẩm");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setName("frameProductManagement"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHeader.setBackground(new java.awt.Color(234, 128, 37));

        lbLogo.setBackground(new java.awt.Color(255, 255, 255));
        lbLogo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbLogo.setForeground(new java.awt.Color(255, 255, 255));
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CFH/images/logo.png"))); // NOI18N
        lbLogo.setText("The CàPhê House");

        lbFrmTitle.setBackground(new java.awt.Color(255, 255, 255));
        lbFrmTitle.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbFrmTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbFrmTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFrmTitle.setText("Quản lí thức uống");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(lbFrmTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(345, 345, 345))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFrmTitle))
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 110));

        jPanelPrdManagement.setBackground(new java.awt.Color(255, 255, 255));

        cbbTenLoai.setBackground(new java.awt.Color(204, 204, 204));
        cbbTenLoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbMaTU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMaTU.setText("Mã thức uống");

        lbPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbPrice.setText("Đơn giá");

        lbNameTU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNameTU.setText("Tên thức uống");

        txtTenThucUong.setBackground(new java.awt.Color(238, 238, 238));
        txtTenThucUong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenThucUong.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTenThucUong.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        txtTenThucUong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenThucUongKeyReleased(evt);
            }
        });

        txtDonGia.setBackground(new java.awt.Color(238, 238, 238));
        txtDonGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDonGia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDonGia.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        txtDonGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDonGiaKeyReleased(evt);
            }
        });

        txtMaThucUong.setEditable(false);
        txtMaThucUong.setBackground(new java.awt.Color(238, 238, 238));
        txtMaThucUong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaThucUong.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMaThucUong.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));

        lblbTenLoai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblbTenLoai.setText("Tên loại");

        tblListSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblListSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thức uống", "Tên thức uống", "Đơn giá", "Mã Loại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblListSP.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblListSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListSP);
        tblListSP.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblListSP.getColumnModel().getColumnCount() > 0) {
            tblListSP.getColumnModel().getColumn(0).setResizable(false);
            tblListSP.getColumnModel().getColumn(1).setResizable(false);
            tblListSP.getColumnModel().getColumn(2).setResizable(false);
            tblListSP.getColumnModel().getColumn(3).setResizable(false);
        }

        btnSua.setBackground(new java.awt.Color(204, 204, 204));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(null);
        btnSua.setBorderPainted(false);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(204, 204, 204));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(null);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLuu.setBackground(new java.awt.Color(204, 204, 204));
        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.setBorder(null);
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 51, 51));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setBorder(null);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(204, 204, 204));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.setBorder(null);
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrdManagementLayout = new javax.swing.GroupLayout(jPanelPrdManagement);
        jPanelPrdManagement.setLayout(jPanelPrdManagementLayout);
        jPanelPrdManagementLayout.setHorizontalGroup(
            jPanelPrdManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrdManagementLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanelPrdManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbbTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPrdManagementLayout.createSequentialGroup()
                        .addGroup(jPanelPrdManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNameTU)
                            .addComponent(lbMaTU, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanelPrdManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPrdManagementLayout.createSequentialGroup()
                                .addGroup(jPanelPrdManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaThucUong, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenThucUong, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelPrdManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblbTenLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))
                            .addGroup(jPanelPrdManagementLayout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanelPrdManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPrdManagementLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPrdManagementLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(301, 301, 301))
            .addGroup(jPanelPrdManagementLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelPrdManagementLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbMaTU, lbNameTU, lbPrice});

        jPanelPrdManagementLayout.setVerticalGroup(
            jPanelPrdManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrdManagementLayout.createSequentialGroup()
                .addGroup(jPanelPrdManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPrdManagementLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanelPrdManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMaTU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaThucUong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanelPrdManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNameTU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTenThucUong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPrdManagementLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelPrdManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanelPrdManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblbTenLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addGroup(jPanelPrdManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );

        jPanelPrdManagementLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbMaTU, txtTenThucUong});

        getContentPane().add(jPanelPrdManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1080, 670));

        setSize(new java.awt.Dimension(798, 751));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    Controller c = new Controller();
    boolean add = false;

    private void tblListSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListSPMouseClicked

        DefaultTableModel model = (DefaultTableModel) tblListSP.getModel();
        int index = tblListSP.getSelectedRow();
        txtMaThucUong.setText((model.getValueAt(index, 0)).toString());
        txtTenThucUong.setText((model.getValueAt(index, 1)).toString());
        txtDonGia.setText(model.getValueAt(index, 2).toString());
        cbbTenLoai.setSelectedItem(model.getValueAt(index, 3).toString());
    }//GEN-LAST:event_tblListSPMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        setButtonSP(false);
        setNullSP();
        setEnableSP(true);
        add = true;
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblListSP.getModel();
        if (tblListSP.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn sản phẩm muốn sửa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            setButtonSP(false);
            setEnableSP(true);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblListSP.getModel();
        if (tblListSP.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn sản phẩm muốn xóa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                int maTU = Integer.parseInt(txtMaThucUong.getText());
                c.DeleteSP(maTU);
                JOptionPane.showMessageDialog(this, "Bạn đã xóa sản phẩm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                model.setRowCount(0);
                showListSP();
            } catch (SQLException sql) {

            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        int gia = 0;
        int maLoai = layMaLoai();
        DefaultTableModel model = (DefaultTableModel) tblListSP.getModel();
        if (add) {
            try {
                if (txtDonGia.getText().equals("") || txtTenThucUong.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Hảy nhập đầy đủ các ô", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    gia = Integer.parseInt(txtDonGia.getText());
                    c.InsertSP(txtTenThucUong.getText(), gia, maLoai);
                    JOptionPane.showMessageDialog(this, "Bạn đã thêm sản phẩm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    model.setRowCount(0);
                    setNullSP();
                    showListSP();
                }
            } catch (SQLException sql) {

            }
        } else {
            int maTU = 0;
            try {
                if (txtDonGia.getText().equals("") || txtTenThucUong.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Hảy nhập đầy đủ các ô", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    maTU = Integer.parseInt(txtMaThucUong.getText());
                    c.UpdateSP(txtTenThucUong.getText(), gia, maLoai, maTU);
                    JOptionPane.showMessageDialog(this, "Bạn đã sửa sản phẩm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    model.setRowCount(0);
                    setNullSP();
                    showListSP();
                }
            } catch (SQLException sql) {

            }
        }
        setEnableSP(false);
        setButtonSP(true);

    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        setNullSP();
        setButtonSP(true);
        setEnableSP(false);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void txtTenThucUongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenThucUongKeyReleased
        // TODO add your handling code here:
        if (!txtTenThucUong.getText().matches("^[a-zA-Z]+$")) {
            JOptionPane.showMessageDialog(this, "Hãy nhập chữ", "Sai kiểu dữ liệu", JOptionPane.INFORMATION_MESSAGE);
            txtTenThucUong.setText("");
        }

    }//GEN-LAST:event_txtTenThucUongKeyReleased

    private void txtDonGiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDonGiaKeyReleased
        // TODO add your handling code here:
        if (!txtDonGia.getText().matches("^[0-9]*$")) {
            JOptionPane.showMessageDialog(this, "Hãy nhập số", "Sai kiểu dữ liệu", JOptionPane.INFORMATION_MESSAGE);
            txtDonGia.setText("");
        }
    }//GEN-LAST:event_txtDonGiaKeyReleased

    int layMaLoai() {
        try {
            ResultSet rs = c.ShowMaLoaiTheoTenLoai(cbbTenLoai.getSelectedItem().toString());
            while (rs.next()) {
                return rs.getInt("MaLoai");
            }
            return rs.getInt("MaLoai");
        } catch (SQLException sql) {
            return 0;
        }
    }

    void showTenLoai() {

        try {
            ResultSet rs = c.ShowLoaiSP();
            while (rs.next()) {
                cbbTenLoai.addItem(rs.getString("TenLoai"));
            }
        } catch (SQLException sql) {

        }
    }

    void showListSP() {
        DefaultTableModel model = (DefaultTableModel) tblListSP.getModel();
        try {
            ResultSet rs = c.ShowListSP();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt("MaTU"), rs.getString("TenThucUong"), rs.getInt("DonGia"), rs.getString("TenLoai")});
            }
        } catch (SQLException sql) {

        }
    }

    void setNullSP() {
        txtTenThucUong.setText("");
        txtDonGia.setText("");
        txtMaThucUong.setText("");
        cbbTenLoai.setSelectedIndex(0);
    }

    void setEnableSP(boolean e) {
        txtTenThucUong.setEditable(e);
        txtDonGia.setEditable(e);
        cbbTenLoai.setEnabled(e);
    }

    void setButtonSP(boolean b) {
        btnThem.setEnabled(b);
        btnSua.setEnabled(b);
        btnXoa.setEnabled(b);
        btnLuu.setEnabled(!b);
        btnHuy.setEnabled(!b);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQLSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQLSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQLSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQLSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQLSP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbTenLoai;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelPrdManagement;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbFrmTitle;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbMaTU;
    private javax.swing.JLabel lbNameTU;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lblbTenLoai;
    private javax.swing.JTable tblListSP;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaThucUong;
    private javax.swing.JTextField txtTenThucUong;
    // End of variables declaration//GEN-END:variables
}
