/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CFH;

/**
 *
 * @author lhd
 */
public class SplashScreen extends javax.swing.JFrame {

  /**
   * Creates new form SplashScreenn
   */
  public SplashScreen() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSlashScreen = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        jProgressBar = new javax.swing.JProgressBar();
        lbLoading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loading...");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSlashScreen.setBackground(new java.awt.Color(234, 128, 37));
        jPanelSlashScreen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbLogo.setBackground(new java.awt.Color(255, 255, 255));
        lbLogo.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lbLogo.setForeground(new java.awt.Color(255, 255, 255));
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CFH/images/logo.png"))); // NOI18N
        lbLogo.setText("The CàPhê House");

        jProgressBar.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar.setForeground(new java.awt.Color(255, 255, 255));

        lbLoading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbLoading.setForeground(new java.awt.Color(255, 255, 255));
        lbLoading.setText("Loading...");

        javax.swing.GroupLayout jPanelSlashScreenLayout = new javax.swing.GroupLayout(jPanelSlashScreen);
        jPanelSlashScreen.setLayout(jPanelSlashScreenLayout);
        jPanelSlashScreenLayout.setHorizontalGroup(
            jPanelSlashScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSlashScreenLayout.createSequentialGroup()
                .addGroup(jPanelSlashScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSlashScreenLayout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSlashScreenLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSlashScreenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbLoading)
                .addGap(382, 382, 382))
        );
        jPanelSlashScreenLayout.setVerticalGroup(
            jPanelSlashScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSlashScreenLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbLoading)
                .addGap(44, 44, 44)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelSlashScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 890, 520));

        setSize(new java.awt.Dimension(883, 422));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new SplashScreen().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelSlashScreen;
    public javax.swing.JProgressBar jProgressBar;
    public javax.swing.JLabel lbLoading;
    private javax.swing.JLabel lbLogo;
    // End of variables declaration//GEN-END:variables
}
