/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CFH;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lhd
 */
public class frmQLLoai extends javax.swing.JFrame {

    /**
     * Creates new form ProductManagement
     */
    public frmQLLoai() {
        initComponents();
        showListLoaiSP();
        txtTenLoai.setEditable(false);
    }

    Controller c = new Controller();

    void showListLoaiSP() {
        DefaultTableModel model = (DefaultTableModel) tblListLoaiSP.getModel();
        try {
            ResultSet rs = c.ShowLoaiSP();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt("MaLoai"), rs.getString("TenLoai")});
            }
        } catch (SQLException sql) {

        }
    }

    void setButtonLoai(boolean b) {
        btnSave.setEnabled(!b);
        btnUpdate.setEnabled(b);
        btnCancel.setEnabled(!b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        lbFrmTitle = new javax.swing.JLabel();
        jPanelPrdManagement = new javax.swing.JPanel();
        lbMaLoai = new javax.swing.JLabel();
        lbNameTU = new javax.swing.JLabel();
        txtTenLoai = new javax.swing.JTextField();
        txtMaLoai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListLoaiSP = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lí sản phẩm");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setName("frameProductManagement"); // NOI18N
        setPreferredSize(new java.awt.Dimension(810, 680));
        setResizable(false);
        setSize(new java.awt.Dimension(810, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHeader.setBackground(new java.awt.Color(234, 128, 37));

        lbLogo.setBackground(new java.awt.Color(255, 255, 255));
        lbLogo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbLogo.setForeground(new java.awt.Color(255, 255, 255));
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CFH/images/logo.png"))); // NOI18N
        lbLogo.setText("The CàPhê House");

        lbFrmTitle.setBackground(new java.awt.Color(255, 255, 255));
        lbFrmTitle.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbFrmTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbFrmTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFrmTitle.setText("Quản lí loại đồ uống");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbFrmTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(513, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFrmTitle))
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 110));

        jPanelPrdManagement.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPrdManagement.setLayout(null);

        lbMaLoai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMaLoai.setText("Mã loại");
        jPanelPrdManagement.add(lbMaLoai);
        lbMaLoai.setBounds(50, 30, 92, 32);

        lbNameTU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNameTU.setText("Tên loại");
        jPanelPrdManagement.add(lbNameTU);
        lbNameTU.setBounds(50, 100, 92, 20);

        txtTenLoai.setBackground(new java.awt.Color(238, 238, 238));
        txtTenLoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenLoai.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTenLoai.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        jPanelPrdManagement.add(txtTenLoai);
        txtTenLoai.setBounds(370, 100, 217, 32);

        txtMaLoai.setEditable(false);
        txtMaLoai.setBackground(new java.awt.Color(238, 238, 238));
        txtMaLoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaLoai.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMaLoai.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        jPanelPrdManagement.add(txtMaLoai);
        txtMaLoai.setBounds(370, 40, 217, 32);

        tblListLoaiSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblListLoaiSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã loại", "Tên loại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblListLoaiSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListLoaiSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListLoaiSP);
        tblListLoaiSP.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblListLoaiSP.getColumnModel().getColumnCount() > 0) {
            tblListLoaiSP.getColumnModel().getColumn(0).setResizable(false);
            tblListLoaiSP.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanelPrdManagement.add(jScrollPane1);
        jScrollPane1.setBounds(10, 227, 580, 330);

        btnUpdate.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.setBorder(null);
        btnUpdate.setBorderPainted(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanelPrdManagement.add(btnUpdate);
        btnUpdate.setBounds(270, 160, 100, 36);

        btnCancel.setBackground(new java.awt.Color(204, 204, 204));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setText("Hủy");
        btnCancel.setBorder(null);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanelPrdManagement.add(btnCancel);
        btnCancel.setBounds(490, 160, 100, 36);

        btnSave.setBackground(new java.awt.Color(204, 204, 204));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setText("Lưu");
        btnSave.setBorder(null);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanelPrdManagement.add(btnSave);
        btnSave.setBounds(380, 160, 100, 36);

        getContentPane().add(jPanelPrdManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 600, 560));

        setSize(new java.awt.Dimension(609, 718));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblListLoaiSP.getModel();
        if (tblListLoaiSP.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn sản phẩm muốn sửa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

        } else {
            txtTenLoai.requestFocus();
            txtTenLoai.setEditable(true);
            setButtonLoai(false);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int ma = 0;
        DefaultTableModel model = (DefaultTableModel) tblListLoaiSP.getModel();
        try {
            if (txtTenLoai.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Hảy nhập đầy đủ các ô", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                ma = Integer.parseInt(txtMaLoai.getText());
                c.UpdateLoaiSP(ma, txtTenLoai.getText());
                JOptionPane.showMessageDialog(this, "Bạn đã sửa sản phẩm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                model.setRowCount(0);
                showListLoaiSP();
            }

        } catch (SQLException sql) {

        }
        setButtonLoai(true);
        txtTenLoai.setEditable(false);
        txtMaLoai.setText("");
        txtTenLoai.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        txtTenLoai.setEditable(false);
        txtMaLoai.setText("");
        txtTenLoai.setText("");
        setButtonLoai(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void tblListLoaiSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListLoaiSPMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblListLoaiSP.getModel();
        int index = tblListLoaiSP.getSelectedRow();
        txtMaLoai.setText((model.getValueAt(index, 0)).toString());
        txtTenLoai.setText((model.getValueAt(index, 1)).toString());
    }//GEN-LAST:event_tblListLoaiSPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQLLoai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQLLoai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQLLoai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQLLoai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQLLoai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelPrdManagement;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbFrmTitle;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbMaLoai;
    private javax.swing.JLabel lbNameTU;
    private javax.swing.JTable tblListLoaiSP;
    private javax.swing.JTextField txtMaLoai;
    private javax.swing.JTextField txtTenLoai;
    // End of variables declaration//GEN-END:variables
}
